import {StyleSheet, Dimensions} from 'react-native';
import {getStatusBarHeight} from 'react-native-status-bar-height';

const styles = StyleSheet.create({
  container: {width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    backgroundColor: 'white',
    alignItems: 'center',
    zIndex: 0,
    flex: 1.2,
    flexDirection: 'column'
  },
  closeWrapper: {
    width: '100%',
    height: '5%',
    marginTop: getStatusBarHeight(),
    alignItems: 'flex-end',
    marginBottom: 30,
  },
  closeButton: {
    width: '10%',
    height: '100%',
    marginTop: '5%',
    marginRight: '5%'
  },
  activeTab: {width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    backgroundColor: '#F8F8F8',
    borderBottomWidth: 0,
    borderColor: '#999999',
  },
  inactiveTab: {width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    backgroundColor: 'white',
    borderColor: '#EAEAEA',
    borderBottomWidth: 1,
    borderBottomColor: '#999999',
  },
  activeWindow: {width: '100%',
     height: '100%',
     alignItems: 'center',
     justifyContent: 'center',
     display: 'flex',
     backgroundColor: '#F8F8F8',
  },
  inactiveWindow: {width: '100%',
     height: '100%',
     alignItems: 'center',
     justifyContent: 'center',
     display: 'none',
     backgroundColor: '#F8F8F8'

  },
  activeType: {width: '90%',
                height: '100%',
                alignItems: 'center',
                justifyContent: 'center',
                backgroundColor: '#999999',
  },
  inactiveType: {width: '90%',
                  height: '100%',
                  alignItems: 'center',
                  justifyContent: 'center',
                  backgroundColor: '#EEEEEE',

  },
  selectedDeleteList: {backgroundColor: 'white',
                      flex: 1,
                      height: '100%',
                      justifyContent: 'center',
                      borderWidth: 1,
                      borderColor: '#AAAAAA',
                      borderBottomWidth: 0
  },
  unselectedDeleteList: {backgroundColor: '#FAFAFA',
                        flex: 1,
                        height: '100%',
                        justifyContent: 'center',
                        borderWidth: 1,
                        borderColor: '#EEEEEE',
                        borderBottomColor: '#AAAAAA'
  },
  selectedDeleteItem: {width: '80%',
                   height: '80%',
                   alignItems: 'center',
                   justifyContent: 'center',
                   backgroundColor: '#999999',
                   padding: 5
  },
  unselectedDeleteItem: {width: '80%',
                   height: '80%',
                   alignItems: 'center',
                   justifyContent: 'center',
                   backgroundColor: '#EEEEEE',
                   padding: 5
  }
});

export default styles;
