import {StyleSheet, Dimensions} from 'react-native';
import {getStatusBarHeight} from 'react-native-status-bar-height';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#07121B',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
  },
  freshPie: {
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    height: Dimensions.get('window').height/15,
    width: '80%',
    marginTop: '5%',
    display: 'flex',
    flexDirection: 'row',
    borderWidth: 2,
    borderColor: '#AAAAAA',
    opacity: 0.8,
  },
  oldPie: {
    backgroundColor: '#b59624',
    alignItems: 'center',
    justifyContent: 'center',
    height: Dimensions.get('window').height/15,
    width: '80%',
    marginTop: '5%',
    display: 'flex',
    flexDirection: 'row',
    borderWidth: 2,
    borderColor: '#AAAAAA',
    opacity: 0.8,
  },
  deadPie: {
    backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
    height: Dimensions.get('window').height/15,
    width: '80%',
    marginTop: '5%',
    display: 'flex',
    flexDirection: 'row',
    borderWidth: 2,
    borderColor: '#AAAAAA',
    opacity: 0.8,
  },
  removedPie: {
    backgroundColor: '#AAAAAA',
    alignItems: 'center',
    justifyContent: 'center',
    height: Dimensions.get('window').height/15,
    width: '80%',
    marginTop: '5%',
    display: 'flex',
    flexDirection: 'row',
    borderWidth: 2,
    borderColor: '#AAAAAA',
    opacity: 0.5,
  },
  pieName: {
    flex: 4,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    height: '100%',
  },
  pieStartTime: {
    borderWidth: 1,
    borderColor: '#EEEEEE',
    height: '100%',
    flex: 0.8,
    alignItems: 'center',
    justifyContent: 'center'
  },
  pieTime: {
    borderWidth: 1,
    borderColor: '#EEEEEE',
    height: '100%',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteButton: {
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    height: '100%',
    flex: 0.8,
  },
  pieRemoveType: {
    borderWidth: 1,
    borderColor: '#EEEEEE',
    height: '100%',
    flex: 1.8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButton: {
    backgroundColor: 'black',
    borderWidth: 1,
    borderColor: '#777777',
    height: '50%',
    width: '35%',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: getStatusBarHeight(),
    marginBottom: 30,
    position: 'absolute',
    left: '32.5%',
    zIndex: 10
  },
  addPieButton: {
    width: '80%',
    height: '80%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEEEEE',
  },
  RemovePieOptionsContainer: {height: '60%',
    width: '60%',
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    top: '20%',
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: 'grey'
  },
  activeRemovePieOptions: {width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    backgroundColor: 'rgba(255,255,255,0.7)',
    alignItems: 'center',
    zIndex: 10,
    flex: 1.2,
    flexDirection: 'column',
    display: 'flex',
  },
  inactiveRemovePieOptions: {width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    backgroundColor: 'rgba(255,255,255,0.7)',
    alignItems: 'center',
    zIndex: 0,
    flex: 1.2,
    flexDirection: 'column',
    display: 'none',
  },
  reasonSelected: {width: '80%',
    flex: 1,
    marginTop: '2%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#999999'},
  reasonUnselected: {width: '80%',
    flex: 1,
    marginTop: '2%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#EEEEEE'},
  numberSelected: {flex: 1,
    height: '80%',
    marginRight: '5%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#999999'},
  numberUnselected: {flex: 1,
    height: '80%',
    marginRight: '5%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEEEEE'},
  removeActive: {flex: 1,
    height: '80%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#db3107'},
  removeInactive: {flex: 1,
    height: '80%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white'},
  removeActiveText: {fontSize: 20,
    color: '#E6E6E6'},
  removeInactiveText: {fontSize: 20,
    color: '#CCCCCC'},
});

export default styles;
