import {StyleSheet, Dimensions} from 'react-native';
import {getStatusBarHeight} from 'react-native-status-bar-height';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#07121B',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
  },
  freshPie: {
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    height: Dimensions.get('window').height/15,
    width: '80%',
    marginTop: '5%',
    display: 'flex',
    flexDirection: 'row',
    borderWidth: 2,
    borderColor: '#AAAAAA',
    opacity: 0.8,
  },
  oldPie: {
    backgroundColor: '#b59624',
    alignItems: 'center',
    justifyContent: 'center',
    height: Dimensions.get('window').height/15,
    width: '80%',
    marginTop: '5%',
    display: 'flex',
    flexDirection: 'row',
    borderWidth: 2,
    borderColor: '#AAAAAA',
    opacity: 0.8,
  },
  deadPie: {
    backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
    height: Dimensions.get('window').height/15,
    width: '80%',
    marginTop: '5%',
    display: 'flex',
    flexDirection: 'row',
    borderWidth: 2,
    borderColor: '#AAAAAA',
    opacity: 0.8,
  },
  removedPie: {
    backgroundColor: '#AAAAAA',
    alignItems: 'center',
    justifyContent: 'center',
    height: Dimensions.get('window').height/15,
    width: '80%',
    marginTop: '5%',
    display: 'flex',
    flexDirection: 'row',
    borderWidth: 2,
    borderColor: '#AAAAAA',
    opacity: 0.5,
  },
  pieName: {
    flex: 4,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    height: '100%',
  },
  pieStartTime: {
    borderWidth: 1,
    borderColor: '#EEEEEE',
    height: '100%',
    flex: 0.8,
    alignItems: 'center',
    justifyContent: 'center'
  },
  pieTime: {
    borderWidth: 1,
    borderColor: '#EEEEEE',
    height: '100%',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteButton: {
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    height: '100%',
    flex: 0.8,
  },
  pieRemoveType: {
    borderWidth: 1,
    borderColor: '#EEEEEE',
    height: '100%',
    flex: 1.8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButton: {
    backgroundColor: 'black',
    borderWidth: 1,
    borderColor: '#777777',
    height: '50%',
    width: '35%',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: getStatusBarHeight(),
    marginBottom: 30,
    position: 'absolute',
    left: '32.5%',
    zIndex: 10
  },
  closeWrapper: {
    width: '100%',
    height: '5%',
    marginTop: getStatusBarHeight(),
    alignItems: 'flex-end',
    marginBottom: 30,
  },
  closeButton: {
    width: '10%',
    height: '100%',
    marginTop: '5%',
    marginRight: '5%'
  },
  addPieButton: {
    width: '80%',
    height: '80%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEEEEE',
  },
  buttonSelect: {
    width: '80%',
    height: '80%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEEEEE',
    padding: 5,
  },
});

export default styles;
